### ISSUE TITLE
Can't get SSL to work on a Docker macvlan setup

### ISSUE THREAD

**Issue by EHRETic** [JonnyWong16/plexpy#2121]
### Describe the Bug

Hi there,

Don't know where the problem is but I think I can't get a working SSL setup because of these 2 issues:
- macvlan setups doesn't allow port mapping so it seems Tautulli will always try to use port mentionned in config.ini file (default 8181)
- it seems Tautulli is unable to "find my certificates" at startup, preventing proper troubleshooting (and I could browse and find them on volume)

I get the following error at container startup:
_WARNING :: MainThread : Tautulli WebStart :: Disabled HTTPS because of missing certificate and key._

I tried the PEM encrypted key and the non encrypted key of my certificate, it didn't help (and I use plenty of self-hosted CA certificates on other apps without any issue)

For the record : it seems like the port is somewhat hard coded to 8181

Very hard to report this issue I have to say, I hope it sufficient to start but I'll provide whatever would be useful.

Thx in advance! 😉

### Steps to Reproduce

Start container with the following compose:
```
version: '3.9'
services:
  tautulli:
    container_name: tautulli-test
    image: ghcr.io/tautulli/tautulli:latest
    
    restart: unless-stopped
    
    volumes:
      - config:/config

    networks:
      default:
        ipv4_address: 192.168.X.X
    
    ports:
      - 80:8181 or 8181:8181 or 443:443
      
    environment:
      PUID: '${PUID}'
      PGID: '${PGID}'
      TZ: '${TZ}'

volumes:
  config:

networks:
  default:
    external: true
    name: multimedia_vlan
```

I've tried modifying the port in config.ini file to 80 and 443, but it didn't help. I can get Tautulli to work on port 80, but I'll have the strange Portainer issue mentioned in screenshots.

### Expected Behavior

Able to be able to use SSL on 443 with my own certificates 😊

### Screenshots

Portainer strange issue when Tautulli is started on a port different than 8181:
![image](https://github.com/Tautulli/Tautulli/assets/28634810/92cf44e9-ae5d-41ee-b81b-6870e2a8d183)

Web interface settings
![image](https://github.com/Tautulli/Tautulli/assets/28634810/31ba5e7f-098d-4572-8ffb-5ba2fde5bdc2)

### Tautulli Version

2.12.5

### Git Branch

master

### Git Commit Hash

b953b951fb46400f7d30a22cdc2791faa8d6e233

### Platform and Version

Docker 

### Python Version

3.9.16

### Browser and Version

Brave 1.57.49

### Link to Logs

https://gist.github.com/EHRETic/33cc728c0f792156a57c382bd40c2506
