### ISSUE TITLE
Woke up to segmentation fault

### ISSUE THREAD

**Issue by treverehrfurth** [JonnyWong16/plexpy#2238]
### Describe the Bug

Got notified by uptime kuma that my Tautulli service was down.
Container log just shows one thing "Segmentation fault".
I've brought down the container, pulled and brought back up, still same issue.
It happened out of nowhere and no clue what's causing this.

Here is my docker compose:
```
version: '3'
services:
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    restart: unless-stopped
    volumes:
      - /srv/dockerdata/tautulli/config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    ports:
      - 8181:8181
```

### Expected Behavior

Tautulli should startup per usual

### Tautulli Version

v2.13.4

### Git Branch

latest

### Git Commit Hash

n/a

### Platform and Version

Ubuntu 22.04

### Python Version

n/a

### Browser and Version

chrome

### Link to Logs

https://gist.github.com/treverehrfurth/c4ab8714fa52b1fb1606c8638898362f
